### ISSUE TITLE
Enable testing for Windows in CI

### ISSUE THREAD

**Issue by pskfyi** [pskfyi/handy#14]
Currently there are multiple issues. May need to be addressed across multiple PRs.

**Comment by AustinArey** [comment]
Running `deno test -A ./fs/glob.test.ts` fails: 
![image](https://user-images.githubusercontent.com/92492121/235506437-49d781d2-90ef-470d-b083-0964865dabc6.png)


Running commands locally confirms `glob(GLOB)` returns empty array.
![image](https://user-images.githubusercontent.com/92492121/235506330-d22812b3-441c-4fa4-8f83-8be6d5234860.png)

**Comment by AustinArey** [comment]
All `deno test -A fs/path` pass. Getting `deno test -A io` to pass...
![image](https://user-images.githubusercontent.com/92492121/235757975-ef4ac4ad-f2a5-486b-895a-887404135ecb.png)
- Using the commands in the terminal directly works `powershell -Command Set-Clipboard "test"` works!
- Using `stdin: piped` and using the Writer does not work (I don't know how to read the final input to the child)
- Replacing writing `text` to `stdin` via the Writer with just pushing `text` to `args` copied to the clipboard successfully
- But the expected output of the test "Hello!" now has "\r\n"
![image](https://user-images.githubusercontent.com/92492121/235757860-eafd087d-190f-476a-b801-7b6794d22fee.png)

I don't understand how the expected "Hello!" of `assertEquals(await paste(), "Hello!");` changed!

**Comment by AustinArey** [comment]
Thanks for investigating: GetClipboard is adding the \r\n. Thanks for the solution:
![image](https://user-images.githubusercontent.com/92492121/235959003-6995e5fd-360b-46b6-8362-12c54653c49e.png)
