### ISSUE TITLE
Enable testing for Linux in CI

### ISSUE THREAD

**Issue by pskfyi** [pskfyi/handy#15]
Issues currently unknown. Needs triaging.

**Comment by AustinArey** [comment]
Running `deno test -A ./fs/glob.test.ts` results
![image](https://user-images.githubusercontent.com/92492121/235504671-cd9bc0f6-baa2-4ae6-ad14-781d71b1b63b.png)

Running the commands locally shows the order of the two results of `glob(GLOB)` is switched:
![image](https://user-images.githubusercontent.com/92492121/235504133-dd104c0b-a5b0-48d6-8bd4-6222ca826b9a.png)

**Comment by AustinArey** [comment]
This is fixed by replacing `assertEquals()` with `assertArrayIncludes()`
Note: this does not fix the empty array on Windows.

![image](https://user-images.githubusercontent.com/92492121/235508720-ca655e66-66c0-4376-b7ad-3bcae4a8b86d.png)

**Comment by AustinArey** [comment]
All tests now pass, but it hangs at the very end... for 5 minutes!

![image](https://user-images.githubusercontent.com/92492121/235587211-d4932d01-46f4-4cc3-bf1a-96a4436234e3.png)

Even though the last test (ts) only takes 6s when run by itself:
![image](https://user-images.githubusercontent.com/92492121/235587395-74ef0fc7-494b-4067-8d09-0e43dfa3e7cd.png)

**Comment by AustinArey** [comment]
After recreating this branch from remote main, all tests pass and it hangs here:
![image](https://user-images.githubusercontent.com/92492121/235590732-8f602d2a-2245-474a-a82f-52c463b89bd3.png)

...before finally showing 4min later:
![image](https://user-images.githubusercontent.com/92492121/235590840-20765235-5154-4403-808d-c97a2610d524.png)
